### ISSUE TITLE
error injecting in 45v game

### ISSUE THREAD

**Issue by Xacker-Volk** [winstxnhdw/lc-hax#238]
the previous version of the cheat worked on the 45th version of the game, but when I saw that new features were added, I reinstalled the cheat, now I have an injection error

Injection failed: SharpMonoInjector.InjectorException: mono_object_get_class() returned NULL
   at SharpMonoInjector.Injector.ThrowIfNull(IntPtr ptr, String methodName)
   at SharpMonoInjector.Injector.GetClassName(IntPtr monoObject)
   at SharpMonoInjector.Injector.RuntimeInvoke(IntPtr method)
   at SharpMonoInjector.Injector.Inject(Byte[] rawAssembly, String namespace, String className, String methodName)
   at Program.<<Main>$>g__Inject|0_0(String targetProcess, FileInfo assembly, String loaderNamespace, String loaderClass, String loaderMethod)
   
   How can I fix it? Thanks for attention.

**Comment by winstxnhdw** [comment]
Is it normal for people to play on an older version?

**Comment by winstxnhdw** [comment]
I see
