### ISSUE TITLE
[Bug]: Game Crashed when launch.bat - Game version V40

### ISSUE THREAD

**Issue by nimash3eshan** [winstxnhdw/lc-hax#296]
### What happened?

"I launched the game and selected the Internet mode. After that, I ran the launch.bat file. And then game crashed"

```Injection failed: SharpMonoInjector.InjectorException: mono_object_get_class() returned NULL
   at SharpMonoInjector.Injector.ThrowIfNull(IntPtr ptr, String methodName)
   at SharpMonoInjector.Injector.GetClassName(IntPtr monoObject)
   at SharpMonoInjector.Injector.RuntimeInvoke(IntPtr method)
   at SharpMonoInjector.Injector.Inject(Byte[] rawAssembly, String namespace, String className, String methodName)
   at Program.<<Main>$>g__Inject|0_0(String targetProcess, FileInfo assembly, String loaderNamespace, String loaderClass, String loaderMethod)]```

### Current Commit Hash

2852af5452cbbc3feb3c85eec8bdd6f5791605a1

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### If you selected "Others" above, please specify the injector you are using.

_No response_

### Log output

Injection failed: SharpMonoInjector.InjectorException: mono_object_get_class() returned NULL
   at SharpMonoInjector.Injector.ThrowIfNull(IntPtr ptr, String methodName)
   at SharpMonoInjector.Injector.GetClassName(IntPtr monoObject)
   at SharpMonoInjector.Injector.RuntimeInvoke(IntPtr method)
   at SharpMonoInjector.Injector.Inject(Byte[] rawAssembly, String namespace, String className, String methodName)
   at Program.<<Main>$>g__Inject|0_0(String targetProcess, FileInfo assembly, String loaderNamespace, String loaderClass, String loaderMethod)

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
We are already at v49

**Comment by GigglingMinister** [comment]
why are you on v40 anyway
