### ISSUE TITLE
[Bug]: Error when launching (merge conflict)

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#464]
### What happened?

error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
MSBuild version 17.8.5+b5265ef37 for .NET
  Determining projects to restore...
  Restored C:\Users\kaide\lc-hax\lc-hax\lc-hax.csproj (in 810 ms).
  1 of 2 projects are up-to-date for restore.
  analysers -> C:\Users\kaide\lc-hax\analysers\bin\Release\netstandard2.1\analysers.dll
C:\Users\kaide\lc-hax\lc-hax\Scripts\Static\State.cs(1,1): error CS8300: Merge conflict marker encountered [C:\Users\ka
ide\lc-hax\lc-hax\lc-hax.csproj]
C:\Users\kaide\lc-hax\lc-hax\Scripts\Static\State.cs(4,1): error CS8300: Merge conflict marker encountered [C:\Users\ka
ide\lc-hax\lc-hax\lc-hax.csproj]
C:\Users\kaide\lc-hax\lc-hax\Scripts\Static\State.cs(9,1): error CS8300: Merge conflict marker encountered [C:\Users\ka
ide\lc-hax\lc-hax\lc-hax.csproj]

Build FAILED.

C:\Users\kaide\lc-hax\lc-hax\Scripts\Static\State.cs(1,1): error CS8300: Merge conflict marker encountered [C:\Users\ka
ide\lc-hax\lc-hax\lc-hax.csproj]
C:\Users\kaide\lc-hax\lc-hax\Scripts\Static\State.cs(4,1): error CS8300: Merge conflict marker encountered [C:\Users\ka
ide\lc-hax\lc-hax\lc-hax.csproj]
C:\Users\kaide\lc-hax\lc-hax\Scripts\Static\State.cs(9,1): error CS8300: Merge conflict marker encountered [C:\Users\ka
ide\lc-hax\lc-hax\lc-hax.csproj]
    0 Warning(s)
    3 Error(s)

Time Elapsed 00:00:01.87
Unhandled exception: System.IO.FileNotFoundException: Could not find file 'C:\Users\kaide\lc-hax\bin\lc-hax.dll'.
File name: 'C:\Users\kaide\lc-hax\bin\lc-hax.dll'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.ReadAllBytes(String path)
   at Program.<<Main>$>g__Inject|0_0(String targetProcess, FileInfo assembly, String loaderNamespace, String loaderClass, String loaderMethod)
   at System.CommandLine.Handler.<>c__DisplayClass6_0`5.<SetHandler>b__0(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
Press any key to continue . . .

### Current Commit Hash

grr4

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I did not have any other mods other than `lc-hax` installed when the issue occurred
- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
You have to discard your changes; which you can do by doing `git reset —hard`. Or re-clone, which works the same.

**Comment by winstxnhdw** [comment]
Seems like you changed something in `State.cs`. You should remove that.

**Comment by joep26020** [comment]
> Seems like you changed something in `State.cs`. You should remove that.

Ok, will do.
