### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Extreme1106** [winstxnhdw/lc-hax#569]
### What happened?

Was working just fine even just two days ago, I load up the launch.bat today however and I keep getting this specific issue. I reinstalled Git and Dotnet SDK and I even reinstalled the repository multiple times. Running as admin doesn't work either as seen in other issues, no fixes are working at all, the console reads as follows:

Already up to date.
  Determining projects to restore...
C:\Users\Extreme\lc-hax\lc-hax\lc-hax.csproj : error NU1202: Package CommunityToolkit.HighPerformance 8.4.0-preview2 is
 not compatible with netstandard2.1 (.NETStandard,Version=v2.1). Package CommunityToolkit.HighPerformance 8.4.0-preview
2 does not support any target frameworks.
C:\Users\Extreme\lc-hax\lc-hax\lc-hax.csproj : error NU1202: Package CommunityToolkit.HighPerformance 8.4.0-preview2 is
 not compatible with netstandard2.1 (.NETStandard,Version=v2.1) / win-x64. Package CommunityToolkit.HighPerformance 8.4
.0-preview2 does not support any target frameworks.
  Restored C:\Users\Extreme\lc-hax\analysers\analysers.csproj (in 185 ms).
  Failed to restore C:\Users\Extreme\lc-hax\lc-hax\lc-hax.csproj (in 189 ms).

Build FAILED.

C:\Users\Extreme\lc-hax\lc-hax\lc-hax.csproj : error NU1202: Package CommunityToolkit.HighPerformance 8.4.0-preview2 is
 not compatible with netstandard2.1 (.NETStandard,Version=v2.1). Package CommunityToolkit.HighPerformance 8.4.0-preview
2 does not support any target frameworks.
C:\Users\Extreme\lc-hax\lc-hax\lc-hax.csproj : error NU1202: Package CommunityToolkit.HighPerformance 8.4.0-preview2 is
 not compatible with netstandard2.1 (.NETStandard,Version=v2.1) / win-x64. Package CommunityToolkit.HighPerformance 8.4
.0-preview2 does not support any target frameworks.
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:00.60
Unhandled exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Extreme\lc-hax\bin\lc-hax.dll'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.ReadAllBytes(String path)
   at Program.<<Main>$>g__Inject|0_0(String targetProcess, FileInfo assembly, String loaderNamespace, String loaderClass, String loaderMethod)
   at System.CommandLine.Handler.<>c__DisplayClass6_0`5.<SetHandler>b__0(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
Press any key to continue . . .

### Current Commit Hash

ac929542960155f1f560934d9d88811cd6004a5e

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I did not have any other mods other than `lc-hax` installed when the issue occurred
- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Let me take a look.

**Comment by Extreme1106** [comment]
any luck?

**Comment by Extreme1106** [comment]
Alright thank you, I will try that when I get the chance and let you know how it goes

**Comment by Extreme1106** [comment]
did the command then ran the batches and they still give me the exact same error

**Comment by winstxnhdw** [comment]
Show your output of doing the command and the batches.

**Comment by Extreme1106** [comment]
PS C:\Users\Extreme\lc-hax> git reset --hard d8f381c2b28a0fcd6da1f05337bbcaecf8358fd3
HEAD is now at d8f381c chore(deps): update github/codeql-action action to v3.27.3 (#566)
PS C:\Users\Extreme\lc-hax> .\requirements
Building SharpMonoInjectorCore! Please be patient as this may take a few minutes!
  Determining projects to restore...
  Restored C:\Users\Extreme\lc-hax\submodules\SharpMonoInjectorCore\SharpMonoInjector.csproj (in 342 ms).
  SharpMonoInjector -> C:\Users\Extreme\lc-hax\submodules\SharpMonoInjectorCore\bin\Release\net8.0-windows\win-x64\Shar
  pMonoInjector.dll
  SharpMonoInjector -> C:\Users\Extreme\lc-hax\submodules\SharpMonoInjectorCore\dist\
Press any key to continue . . .
PS C:\Users\Extreme\lc-hax> .\launch
Updating d8f381c..9421436
Fast-forward
 .github/workflows/codeql.yml | 6 +++---
 lc-hax/lc-hax.csproj         | 6 +++---
 lc-hax/packages.lock.json    | 6 +++---
 3 files changed, 9 insertions(+), 9 deletions(-)
  Determining projects to restore...
C:\Users\Extreme\lc-hax\lc-hax\lc-hax.csproj : error NU1202: Package CommunityToolkit.HighPerformance 8.4.0-preview2 is
 not compatible with netstandard2.1 (.NETStandard,Version=v2.1). Package CommunityToolkit.HighPerformance 8.4.0-preview
2 does not support any target frameworks.
C:\Users\Extreme\lc-hax\lc-hax\lc-hax.csproj : error NU1202: Package CommunityToolkit.HighPerformance 8.4.0-preview2 is
 not compatible with netstandard2.1 (.NETStandard,Version=v2.1) / win-x64. Package CommunityToolkit.HighPerformance 8.4
.0-preview2 does not support any target frameworks.
  Failed to restore C:\Users\Extreme\lc-hax\lc-hax\lc-hax.csproj (in 538 ms).
  1 of 2 projects are up-to-date for restore.

Build FAILED.

C:\Users\Extreme\lc-hax\lc-hax\lc-hax.csproj : error NU1202: Package CommunityToolkit.HighPerformance 8.4.0-preview2 is
 not compatible with netstandard2.1 (.NETStandard,Version=v2.1). Package CommunityToolkit.HighPerformance 8.4.0-preview
2 does not support any target frameworks.
C:\Users\Extreme\lc-hax\lc-hax\lc-hax.csproj : error NU1202: Package CommunityToolkit.HighPerformance 8.4.0-preview2 is
 not compatible with netstandard2.1 (.NETStandard,Version=v2.1) / win-x64. Package CommunityToolkit.HighPerformance 8.4
.0-preview2 does not support any target frameworks.
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:00.93
Unhandled exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Extreme\lc-hax\bin\lc-hax.dll'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.ReadAllBytes(String path)
   at Program.<<Main>$>g__Inject|0_0(String targetProcess, FileInfo assembly, String loaderNamespace, String loaderClass, String loaderMethod)
   at System.CommandLine.Handler.<>c__DisplayClass6_0`5.<SetHandler>b__0(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
Press any key to continue . . .

**Comment by winstxnhdw** [comment]
Ah, I forgot to tell you. Use launch-dev instead. The original batch file auto updates.

**Comment by Extreme1106** [comment]
My bad, I forgot launch-dev automatically updates, I ran those commands in order and it works again! I still don't know what caused the issue originally but as long as it works at all that's awesome, thank you for your help

**Comment by winstxnhdw** [comment]
I couldn't replicate your problem after all.
